feat: service 공통 exception(NotFoundException) 처리
KNU-CSE14/edio_backend pull request #21
Opened 2024-11-05 04:43 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- service 공통 exception(NotFoundException) 처리

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [ ] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-11-05 15:45 UTC, GuardJo requested changes
리뷰어는 아니지만 일단 남겨봄

2024-11-05 15:45 UTC, GuardJo commented on src/main/java/com/edio/common/exception/NotFoundException.java
> +        super(HttpStatus.NOT_FOUND, String.format("%s not found: %d", serviceName, id));
의도하는 바에 따르면, 특정 Entity 객체를 찾지 못했을 경우 어떠한 Entity 객체인지 메시지를 남기고 싶어하는 듯함
허나 해당 message format 처럼 단순 리터럴 문자열의 경우, 해당 Exception 인스턴스를 초기화하는 사용자가 어떠한 문자열이든 삽입할 수 있는 문제 존재
- 이런 경우 리터럴 문자열 대신 해당 Entity 객체의 Class 객체를 입력받는 것이 보다 나을 듯함
- 혹은 추후 Entity 객체들의 상위 Class가 존재할 경우, 해당 타입 하위 객체들만 입력으로 들어올 수 있도록 하는 것도 좋을 듯함

2024-11-05 15:45 UTC, GuardJo commented on src/main/java/com/edio/user/service/AccountServiceImpl.java
>          Accounts account = accountRepository.findByLoginIdAndStatus(loginId, "active")
특정 상태를 저장하는 필드값의 경우, "active"와 같이 리터럴 문자열 타입으로 두면, 어떠한 문자열이라도 입력이 가능함
이는 컴파일 시점에 별도로 체크할 수 없기에 인적 오류를 발생할 가능성이 높음

- 이러한 상태 및 특정 값으로 한정된 필드를 사용할 경우 Enum 객체를 사용하는 것이 보다 나을 듯함
- JPA에서는 enum 객체를 컬럼에 매핑할 수 있는 enumerate 어노테이션도 제공함

2024-11-06 04:23 UTC, zz106603 commented on src/main/java/com/edio/common/exception/NotFoundException.java
> +        super(HttpStatus.NOT_FOUND, String.format("%s not found: %d", serviceName, id));
Class<T> entityClass 파라미터를 적용해서 entityClass.getSimpleName()으로 전달될 수 있도록 수정

2024-11-06 04:23 UTC, zz106603 commented on src/main/java/com/edio/common/exception/NotFoundException.java
> +        super(HttpStatus.NOT_FOUND, String.format("%s not found: %d", serviceName, id));
> 의도하는 바에 따르면, 특정 Entity 객체를 찾지 못했을 경우 어떠한 Entity 객체인지 메시지를 남기고 싶어하는 듯함 허나 해당 message format 처럼 단순 리터럴 문자열의 경우, 해당 Exception 인스턴스를 초기화하는 사용자가 어떠한 문자열이든 삽입할 수 있는 문제 존재
> 
> * 이런 경우 리터럴 문자열 대신 해당 Entity 객체의 Class 객체를 입력받는 것이 보다 나을 듯함
> * 혹은 추후 Entity 객체들의 상위 Class가 존재할 경우, 해당 타입 하위 객체들만 입력으로 들어올 수 있도록 하는 것도 좋을 듯함

Class entityClass 파라미터를 적용해서 entityClass.getSimpleName()으로 전달될 수 있도록 수정

2024-11-06 04:29 UTC, zz106603 commented on src/main/java/com/edio/user/service/AccountServiceImpl.java
>          Accounts account = accountRepository.findByLoginIdAndStatus(loginId, "active")
> 특정 상태를 저장하는 필드값의 경우, "active"와 같이 리터럴 문자열 타입으로 두면, 어떠한 문자열이라도 입력이 가능함 이는 컴파일 시점에 별도로 체크할 수 없기에 인적 오류를 발생할 가능성이 높음
> 
> * 이러한 상태 및 특정 값으로 한정된 필드를 사용할 경우 Enum 객체를 사용하는 것이 보다 나을 듯함
> * JPA에서는 enum 객체를 컬럼에 매핑할 수 있는 enumerate 어노테이션도 제공함

Enumerated를 사용하여 Enum 객체를 사용하도록 수정(JPA설정 부분이라 jpa-setting브랜치에서 작업)

2024-11-06 04:35 UTC, jsjouo249 approved these changes

2024-11-06 05:14 UTC, GuardJo approved these changes
👍

2024-11-06 05:14 UTC, merged