add: JPA 어노테이션 수정, 사용자(계정, 정보) 등록 테스트 코드 작성, Swagger 토큰 검증 추가
KNU-CSE14/edio_backend pull request #22
Opened 2024-11-05 06:30 UTC by zz106603

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] ✨ New feature (a non-breaking change that adds functionality)

### 📚 Description

- JPA 어노테이션(생성자 등) 수정
- BaseEntity로 Id 컬럼 공통 관리
- Account 및 Member 엔티티 수정 및 DB저장 테스트 코드 작성(UserControllerTests)
- Swagger 토큰 접근을 위한 bearer 적용 

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [x] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-11-05 16:07 UTC, GuardJo requested changes
본 김에 리뷰해봄

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/common/domain/BaseEntity.java
> +    private Long id;
식별키 필드명이 전부 동일하면 공통화 시키는 것도 괜찮을 듯함
하지만 Auditing 요소 확인 요청한건, Auditing 기능 요소 중 createdDate 나 LastModifiedDate 어노테이션을 통해 생성 일자와 수정 일자를 자동으로 저장 및 갱신하도록 하는데 있었음

- 생성 일자와 수정 일자를 별도로 관리할 필요 없이, JpaAuditing 이 활성화된 하위 Entity들은 위에 언급된 어노테이션을 통해 자동으로 일자 갱신이 가능함
- 또한 추후 수정이나 생성 시점에 어떤 인원이 해당 데이터를 처리했는지 등도 식별 가능하도록 createdBy 나 lastModifedBy 등의 어노테이션도 존재함

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/controller/AccountController.java
> +    @PostMapping("/account/create")
일반적으로 Restful API URL에는 동사는 넣지 않음
이는 Restful API의 특성 자체가 동적인 표현을 HTTP Method로 표현하고 있기에 위와 같은 경우 이미 POST method 가 어떠한 데이터의 생성 혹은 작성을 뜻하고 있음

- 그냥 POST : /accounts 등으로 충분함

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/domain/Accounts.java
> +    @Column(updatable = false)
CreatedDate 어노테이션이 추가되었으면, updatable은 알아서 false로 덮어씌워짐
단 현재 해당 필드는 setter 가 존재하는 형태이므로, setter 도 지워야 코드상으로도 완전한 불변성을 보장할 수 있을 듯함

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/domain/Accounts.java
> +    @Column(nullable = false)
앞선 #21 PR 참고바람

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/domain/Members.java
>      private String email;
뭔가 email은 UK여야 할 듯 함, 해당 의견은 논의해보는것도 좋을 듯

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/domain/Members.java
>      private String lastName;
혹시 familyName 아닐까...

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/model/reponse/AccountResponse.java
>  public class AccountResponse {
단순 Req/Res 와 같은 VO나 별도 로직 없는 DTO 객체같은 경우들은 Java 11이었나 14부터 추가된 record 객체를 쓰면 보다 간단함

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/model/reponse/AccountResponse.java
>  public class AccountResponse {
대신 Builder 어노테이션은 못씀 ㅋ

2024-11-05 16:07 UTC, GuardJo commented on src/main/java/com/edio/user/service/AccountServiceImpl.java
> +    public AccountResponse createAccount(Accounts account) {
해당 class 내 Transaction 관련 처리가 안보임
특히 해당 메소드는 신규 생성 메소드이기에 Transaction 설정이 특히 더 필요함

- JPA는 트랜잭션을 기반으로 영속 컨택스트를 관리하기에, 트랜잭션 처리가 중요함, Transactional 어노테이션 활용
- 별도 트랜잭션 처리가 없을 경우 엔드포인트 메소드인 Controller 단 까지 트랜잭션이 살아있게 됨 (이는 jpa 설정 중 open-view? 였나 설정으로 껐다 킬 수 있긴함)

2024-11-05 16:07 UTC, GuardJo commented on src/test/java/com/edio/user/UserControllerUnitTests.java
> +    private AccountServiceImpl accountService;
클래스 이름과 다르게 AccountService 에 대한 단위 테스트 였음

- 서비스 로직 단위 테스트를 위한 요소면 AccountServiceTest 인게 더 자연스러울 듯함
- 또한 관례 및 패키지 범위 접근 가능 객체 등의 시점에서 테스트 클래스들은 원본 클래스와 동일한 패키지명을 유지함
- 혹, controller 클래스에 대한 단위 테스트를 바랄 경우, WebMvcTest 어노테이션을 찾아보면 됨

2024-11-06 02:34 UTC, zz106603 commented on src/main/java/com/edio/user/domain/Members.java
>      private String email;
> 뭔가 email은 UK여야 할 듯 함, 해당 의견은 논의해보는것도 좋을 듯

oAuth 로그인 진행할 때 애플 계정은 구글, 네이버 등 가능해서 중복 허용

2024-11-06 05:33 UTC, zz106603 commented on src/test/java/com/edio/user/UserControllerUnitTests.java
> +    private AccountServiceImpl accountService;
> 클래스 이름과 다르게 AccountService 에 대한 단위 테스트 였음
> 
> * 서비스 로직 단위 테스트를 위한 요소면 AccountServiceTest 인게 더 자연스러울 듯함
> * 또한 관례 및 패키지 범위 접근 가능 객체 등의 시점에서 테스트 클래스들은 원본 클래스와 동일한 패키지명을 유지함
> * 혹, controller 클래스에 대한 단위 테스트를 바랄 경우, WebMvcTest 어노테이션을 찾아보면 됨

현재 Account Service에 대한 내용은 service패키지 하위에 AccountServiceTests로 변경

2024-11-06 07:00 UTC, zz106603 commented on src/main/java/com/edio/common/domain/BaseEntity.java
> +    private Long id;
> 식별키 필드명이 전부 동일하면 공통화 시키는 것도 괜찮을 듯함 하지만 Auditing 요소 확인 요청한건, Auditing 기능 요소 중 createdDate 나 LastModifiedDate 어노테이션을 통해 생성 일자와 수정 일자를 자동으로 저장 및 갱신하도록 하는데 있었음
> 
> * 생성 일자와 수정 일자를 별도로 관리할 필요 없이, JpaAuditing 이 활성화된 하위 Entity들은 위에 언급된 어노테이션을 통해 자동으로 일자 갱신이 가능함
> * 또한 추후 수정이나 생성 시점에 어떤 인원이 해당 데이터를 처리했는지 등도 식별 가능하도록 createdBy 나 lastModifedBy 등의 어노테이션도 존재함

공통 BaseEntity로 Id, createAt, updateAt 추가 및 @CreateDate, @LastModifiedDate 적용

2024-11-06 07:00 UTC, zz106603 commented on src/main/java/com/edio/user/controller/AccountController.java
> +    @PostMapping("/account/create")
> 일반적으로 Restful API URL에는 동사는 넣지 않음 이는 Restful API의 특성 자체가 동적인 표현을 HTTP Method로 표현하고 있기에 위와 같은 경우 이미 POST method 가 어떠한 데이터의 생성 혹은 작성을 뜻하고 있음
> 
> * 그냥 POST : /accounts 등으로 충분함

단일 계정 등록이기 때문에 POST /api/account로 수정

2024-11-06 07:01 UTC, zz106603 commented on src/main/java/com/edio/user/domain/Accounts.java
> +    @Column(updatable = false)
> CreatedDate 어노테이션이 추가되었으면, updatable은 알아서 false로 덮어씌워짐 단 현재 해당 필드는 setter 가 존재하는 형태이므로, setter 도 지워야 코드상으로도 완전한 불변성을 보장할 수 있을 듯함

- Setter는 제거, Builder를 통해서 객체 생성할 수 있도록 수정
- CreateDate 어노테이션이 추가되어도 updateable은 true이기 때문에 false로 적용은 유지

2024-11-06 07:08 UTC, zz106603 commented on src/main/java/com/edio/user/domain/Members.java
>      private String lastName;
> 혹시 familyName 아닐까...

lastName -> famliyName
firstName -> givenName
fullName -> name으로 변경 완료

2024-11-06 07:08 UTC, zz106603 commented on src/main/java/com/edio/user/model/reponse/AccountResponse.java
>  public class AccountResponse {
> 단순 Req/Res 와 같은 VO나 별도 로직 없는 DTO 객체같은 경우들은 Java 11이었나 14부터 추가된 record 객체를 쓰면 보다 간단함

- record로 변경하여 response 객체 수정 완료

2024-11-06 07:08 UTC, zz106603 commented on src/main/java/com/edio/user/service/AccountServiceImpl.java
> +    public AccountResponse createAccount(Accounts account) {
> 해당 class 내 Transaction 관련 처리가 안보임 특히 해당 메소드는 신규 생성 메소드이기에 Transaction 설정이 특히 더 필요함
> 
> * JPA는 트랜잭션을 기반으로 영속 컨택스트를 관리하기에, 트랜잭션 처리가 중요함, Transactional 어노테이션 활용
> * 별도 트랜잭션 처리가 없을 경우 엔드포인트 메소드인 Controller 단 까지 트랜잭션이 살아있게 됨 (이는 jpa 설정 중 open-view? 였나 설정으로 껐다 킬 수 있긴함)

- @Transactional 어노테이션 적용

2024-11-07 05:27 UTC, GuardJo requested changes

2024-11-07 05:27 UTC, GuardJo commented on src/main/java/com/edio/user/controller/AccountController.java
> +    public AccountResponse createAccount(@RequestBody Accounts account){
Accounts Entity 자체를 requestBody로 받게 되면, id 값도 외부에서 주입해서 넣어줄 수 있게됨, 이는 DB에 직접 insert 하는 것과 별반 다르지 않을 정도이며, 이에 따라 데이터 조작이 클라이언트에서도 가능해지는 문제 발생

- Account 생성에 필수적인 요소들만 별도로 받아서 처리하도록 하는것이 좋음

2024-11-07 05:27 UTC, GuardJo commented on src/main/java/com/edio/user/controller/MemberController.java
> +    public MemberResponse createAccount(@RequestBody Members member){
Account 쪽과 마찬가지

2024-11-07 05:27 UTC, GuardJo commented on src/main/java/com/edio/user/domain/Accounts.java
> +    private AccountRole roles;
단수형인데 왜 이름이 복수형인지?
사실 Entity나 테이블명들도 복수인게 의문

2024-11-07 05:27 UTC, GuardJo commented on src/main/java/com/edio/user/model/reponse/AccountResponse.java
> +                account.isStatus(),
status라는 필드명 자체가 올바르지 않음
논의때는 해당 필드가 삭제 여부 값을 저장하는 듯한데, status는 너무 모호함, 또한 boolean 값인데 단순 값명사가 들어가 있기에 혼동됨

2024-11-07 05:27 UTC, GuardJo commented on src/test/java/com/edio/user/UserControllerUnitTests.java
> +    private AccountServiceImpl accountService;
service 하위가 아닌 service.unit 하위로 보이는데 중간 패키지를 추가한 이유가 있는지?

2024-11-07 07:29 UTC, zz106603 commented on src/test/java/com/edio/user/UserControllerUnitTests.java
> +    private AccountServiceImpl accountService;
> service 하위가 아닌 service.unit 하위로 보이는데 중간 패키지를 추가한 이유가 있는지?

단위, 통합 테스트를 구분하기 위한 패키지였는데 통합 테스트는 service 단계에서 필요없다고 판단하여 수정 진행

2024-11-07 07:51 UTC, zz106603 commented on src/main/java/com/edio/user/controller/AccountController.java
> +    public AccountResponse createAccount(@RequestBody Accounts account){
> Accounts Entity 자체를 requestBody로 받게 되면, id 값도 외부에서 주입해서 넣어줄 수 있게됨, 이는 DB에 직접 insert 하는 것과 별반 다르지 않을 정도이며, 이에 따라 데이터 조작이 클라이언트에서도 가능해지는 문제 발생
> 
> * Account 생성에 필수적인 요소들만 별도로 받아서 처리하도록 하는것이 좋음

Account 및 Member에 Request 객체를 만들어서 받을 수 있도록 수정

2024-11-07 07:52 UTC, zz106603 commented on src/main/java/com/edio/user/domain/Accounts.java
> +    private AccountRole roles;
> 단수형인데 왜 이름이 복수형인지? 사실 Entity나 테이블명들도 복수인게 의문

다른 PR에서 수정 예정~

2024-11-07 07:57 UTC, zz106603 commented on src/main/java/com/edio/user/model/reponse/AccountResponse.java
> +                account.isStatus(),
> status라는 필드명 자체가 올바르지 않음 논의때는 해당 필드가 삭제 여부 값을 저장하는 듯한데, status는 너무 모호함, 또한 boolean 값인데 단순 값명사가 들어가 있기에 혼동됨

status를 is_deleted 컬럼으로 수정 및 코드 반영했습니다.

2024-11-07 16:11 UTC, GuardJo requested changes

2024-11-07 16:11 UTC, GuardJo commented on src/main/java/com/edio/common/security/CustomOAuth2UserService.java
> +        Accounts account = accountRepository.findByLoginIdAndIsDeleted(email, true)
이거 true면 삭제 된거 아닌지?

2024-11-07 16:11 UTC, GuardJo commented on src/main/java/com/edio/user/service/AccountServiceImpl.java
> +        Accounts savedAccount = accountRepository.findByLoginIdAndIsDeleted(accountRequest.getLoginId(), false)
해당 로직은 이미 계정이 존재하든 안하든 조회 쿼리 + 생성 쿼리, 2번의 쿼리가 필수적임

하지만 loginId는 어차피 UK 니까 굳이 조회 쿼리를 보내서 확인할 필요 없이 바로 생성 쿼리 날려도 됨
만약 이미 생성된 계정이면 loginId 가 UK 이기에, 무결성 제약 예외가 발생할 것이고, 해당 예외를 잡아서 그 때 조회 쿼리를 날리면, 쿼리 1회로도 마무리 될 수도 있음 (물론 중복되면 2회처리 지만...)

애초에 이미 존재하는 계정 생성 요청은 무결성 제약 예외를 409 Conflict나 400 BadReq 와 같은 클라이언트 오류 코드로 반환하는 것이 더 일반적임

2024-11-07 16:11 UTC, GuardJo commented on src/main/java/com/edio/user/model/request/AccountRequest.java
> +public class AccountRequest {
record는 선택사항, 하지만 객체명을 정할 땐 보다 상세하게 정하는것이 좋을 듯함
위와 같은 AccountRequest의 경우 다른 사용자가 볼 때 어떤 요청에 대한 처리 객체인지 식별하기 어려움
- 심지어 필드 하나라 전체 프로세스를 봐야지만 이 객체가 계정 생성 처리 요청 객체라는 것을 식별할 수 있음

2024-11-07 16:11 UTC, GuardJo commented on src/main/java/com/edio/user/model/request/MemberRequest.java
> +public class MemberRequest {
AccountRequest와 동일한 이유
- 또한 class 객체 및 lombok 사용 시에 이와 같은 단순 VO 객체는 Getter/Setter 따로 할 필요 없이 Data 어노테이션 하나로 만사 오케이임 (Data = Getter + Setter + ToString + EqualsAndHashCode 를 포함함)

2024-11-07 16:12 UTC, GuardJo commented on src/main/java/com/edio/user/service/AccountServiceImpl.java
> +        Accounts savedAccount = accountRepository.findByLoginIdAndIsDeleted(accountRequest.getLoginId(), false)
해당 사항은 우선 이러한 방법도 고려만 해보고, 수정 할지 여부 등은 편한대로 해도 됨

2024-11-08 04:22 UTC, zz106603 commented on src/main/java/com/edio/common/security/CustomOAuth2UserService.java
> +        Accounts account = accountRepository.findByLoginIdAndIsDeleted(email, true)
> 이거 true면 삭제 된거 아닌지?

오타 수정했습니다

2024-11-08 04:53 UTC, zz106603 commented on src/main/java/com/edio/user/service/AccountServiceImpl.java
> +        Accounts savedAccount = accountRepository.findByLoginIdAndIsDeleted(accountRequest.getLoginId(), false)
> 해당 로직은 이미 계정이 존재하든 안하든 조회 쿼리 + 생성 쿼리, 2번의 쿼리가 필수적임
> 
> 하지만 loginId는 어차피 UK 니까 굳이 조회 쿼리를 보내서 확인할 필요 없이 바로 생성 쿼리 날려도 됨 만약 이미 생성된 계정이면 loginId 가 UK 이기에, 무결성 제약 예외가 발생할 것이고, 해당 예외를 잡아서 그 때 조회 쿼리를 날리면, 쿼리 1회로도 마무리 될 수도 있음 (물론 중복되면 2회처리 지만...)
> 
> 애초에 이미 존재하는 계정 생성 요청은 무결성 제약 예외를 409 Conflict나 400 BadReq 와 같은 클라이언트 오류 코드로 반환하는 것이 더 일반적임

이 방법이 더 낫다고 판단하여 바로 save 후에 409 Conflict를 응답하도록 수정

2024-11-08 04:56 UTC, zz106603 commented on src/main/java/com/edio/user/model/request/AccountRequest.java
> +public class AccountRequest {
> record는 선택사항, 하지만 객체명을 정할 땐 보다 상세하게 정하는것이 좋을 듯함 위와 같은 AccountRequest의 경우 다른 사용자가 볼 때 어떤 요청에 대한 처리 객체인지 식별하기 어려움
> 
> * 심지어 필드 하나라 전체 프로세스를 봐야지만 이 객체가 계정 생성 처리 요청 객체라는 것을 식별할 수 있음

AccountCreateRequest라는 객체명으로 변경 완료

2024-11-08 04:57 UTC, zz106603 commented on src/main/java/com/edio/user/model/request/MemberRequest.java
> +public class MemberRequest {
> AccountRequest와 동일한 이유
> 
> * 또한 class 객체 및 lombok 사용 시에 이와 같은 단순 VO 객체는 Getter/Setter 따로 할 필요 없이 Data 어노테이션 하나로 만사 오케이임 (Data = Getter + Setter + ToString + EqualsAndHashCode 를 포함함)

@Data로 적용 완료

2024-11-08 06:24 UTC, GuardJo approved these changes
👍

2024-11-08 08:53 UTC, jsjouo249 approved these changes

2024-11-08 10:11 UTC, merged