Add/ Folder 관련 CRUD 기능 개발
KNU-CSE14/edio_backend pull request #25
Opened 2024-11-07 07:23 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- Folder 관련 패키지 추가(controller, domain, service, repository, model)
- 등록, 수정, 삭제, 조회 기능 개발

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [x] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-11-07 16:39 UTC, GuardJo requested changes
힘내세요

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/EdioBackendApplication.java
> +@EnableJpaAuditing  // JPA Auditing 활성화
git으로 pull 떙겨 오는건 왠만하면 특정 브랜치가 아닌 main 브랜치만 pull 떠와야함
- 어떤 pr을 먼저 merge 하는냐에 따라 충돌 날 수 있음 (pr 올렸을 땐 충돌 안뜨지만 다른 pr이 merge 되면 충돌 나는 경우)
- 결국 충돌 수정을 위해 다시 pull 떠올 것이며, 결국 두 번 일하게 됨

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/controller/FolderController.java
> +    @PutMapping("/folder/{id}")
PATCH랑 PUT은 약간 다른 이벤트임
- PATCH가 아예 어떤 값을 바꾸는 거고
- PUT은 List 같은 여러 데이터 집합에 추가 하거나 빼는 등의 작업 느낌

얘 같은 경우 이름이라는 단일 요소에 대해서 값을 바꾸는 거니 PATCH가 더 맞음

PUT 예시 : 특정 유저 그룹에 유저를 더하거나 빼는 작업

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/domain/Folder.java
> +    public Folder deleteeFields(boolean isDeleted) {
오타

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/domain/Folder.java
> +    public Folder deleteeFields(boolean isDeleted) {
그리고 혹시 변환 된 객체를 따로 반환받는 이유가 있는지?

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/model/request/FolderRequest.java
> +public class FolderRequest {
앞선 #22 와 동일

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/repository/FolderRepository.java
> +    List<Folder> findByAccountIdAndIsDeleted(Long accountId, boolean isDeleted);
findByXXX 도 되긴 하는데 반환 데이터가 다수일 경우는 보통 findAllXXX 를 씀

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +    private Logger logger = LoggerFactory.getLogger(this.getClass());
lombok의 slf4j 어노테이션을 추가하면 logger 초기화 할 필요 없음 
- log라는 명칭으로 사용 가능

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        Map<Long, FolderResponse> folderMap = folders.stream()
Stream API 사용할거면 위에 sort() 도 stream API의 sorted() 로 붙여 버리는게 stream 레벨에서 한꺼번에 처리할 수 있으니 더 나음

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        for (Folder folder : folders) {
이러한 요소가 이제 Folder의 parentId 대신 Folder 참조 객체를 사용하면 간단하게 풀 수 있음

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        for (Folder folder : folders) {
JPA 특 : Entity 간 참조 관계 구성

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        folderRepository.save(existingFolder);
JPA 특 : 트랜잭션 내에서 Entity의 변경 작업은 save() 등의 호출 없이도 트랜잭션 commit 시점에 자동으로 반영됨

2024-11-07 16:39 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        folderRepository.save(existingFolder);
이하 동문

2024-11-08 05:02 UTC, zz106603 commented on src/main/java/com/edio/EdioBackendApplication.java
> +@EnableJpaAuditing  // JPA Auditing 활성화
> git으로 pull 떙겨 오는건 왠만하면 특정 브랜치가 아닌 main 브랜치만 pull 떠와야함
> 
> * 어떤 pr을 먼저 merge 하는냐에 따라 충돌 날 수 있음 (pr 올렸을 땐 충돌 안뜨지만 다른 pr이 merge 되면 충돌 나는 경우)
> * 결국 충돌 수정을 위해 다시 pull 떠올 것이며, 결국 두 번 일하게 됨

앞으로 그렇게 할 예정입니다. (현재 상황은 추가 개발 요구사항이 merge되지 않은 이전 PR에 너무 의존적인 상황이라)

2024-11-08 05:18 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/controller/FolderController.java
> +    @PutMapping("/folder/{id}")
> PATCH랑 PUT은 약간 다른 이벤트임
> 
> * PATCH가 아예 어떤 값을 바꾸는 거고
> * PUT은 List 같은 여러 데이터 집합에 추가 하거나 빼는 등의 작업 느낌
> 
> 얘 같은 경우 이름이라는 단일 요소에 대해서 값을 바꾸는 거니 PATCH가 더 맞음
> 
> PUT 예시 : 특정 유저 그룹에 유저를 더하거나 빼는 작업

변경했습니다.

2024-11-08 05:20 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/repository/FolderRepository.java
> +    List<Folder> findByAccountIdAndIsDeleted(Long accountId, boolean isDeleted);
> findByXXX 도 되긴 하는데 반환 데이터가 다수일 경우는 보통 findAllXXX 를 씀

findAll로 수정 완료

2024-11-08 05:22 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +    private Logger logger = LoggerFactory.getLogger(this.getClass());
> lombok의 slf4j 어노테이션을 추가하면 logger 초기화 할 필요 없음
> 
> * log라는 명칭으로 사용 가능

@Slf4j 적용해서 log명칭 사용하도록 수정 완료

2024-11-08 05:23 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        Map<Long, FolderResponse> folderMap = folders.stream()
> Stream API 사용할거면 위에 sort() 도 stream API의 sorted() 로 붙여 버리는게 stream 레벨에서 한꺼번에 처리할 수 있으니 더 나음

처리했습니다.

2024-11-08 06:06 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/domain/Folder.java
> +    public Folder deleteeFields(boolean isDeleted) {
> 그리고 혹시 변환 된 객체를 따로 반환받는 이유가 있는지?

Setter 적용

2024-11-08 06:06 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        folderRepository.save(existingFolder);
> JPA 특 : 트랜잭션 내에서 Entity의 변경 작업은 save() 등의 호출 없이도 트랜잭션 commit 시점에 자동으로 반영됨

적용했습니다.

2024-11-08 06:17 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        for (Folder folder : folders) {
> 이러한 요소가 이제 Folder의 parentId 대신 Folder 참조 객체를 사용하면 간단하게 풀 수 있음

추후에 변경 예정

2024-11-08 08:38 UTC, GuardJo approved these changes
👍

2024-11-08 08:54 UTC, jsjouo249 approved these changes

2024-11-10 05:32 UTC, merged