Add/ jwt 사용자 검증 추가 및 예외 응답 처리
KNU-CSE14/edio_backend pull request #33
Opened 2024-11-11 06:52 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- jwt 검사 시 사용자(loginId)검증 추가 및 UserDetails에 id, password, role 저장
- 사용자 검증 실패했을 시 401 응답 추가(UsernameNotFoundException을 통해 처리해야 함)
- jwt 사용자 검증 Test 로직 추가

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [x] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-11-12 13:23 UTC, GuardJo requested changes
우선 JWT 토큰 발급 부분만 좀 쪼개주세요

2024-11-12 13:23 UTC, GuardJo commented on src/main/java/com/edio/common/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler {
Spring에 기본적인 Exception들에 대한 handling을 지원하는 ResponseEntityExceptionHandler 객체가 존재함
- 시간 될 때 참고 바람

2024-11-12 13:23 UTC, GuardJo commented on src/main/java/com/edio/common/security/CustomUserDetailsService.java
> +    public CustomUserDetailsService(AccountRepository accountRepository) {
lombok 을 적극적으로 활용합시다

- 또한 UserDetailsService와 같은 함수형 인터페이스는 구현체를 굳이 구성하지 않아도 Configuration 객체 내 Lambda 형식으로 빼면 코드 수를 보다 더 줄일 수 있음

2024-11-12 13:23 UTC, GuardJo commented on src/main/java/com/edio/common/security/jwt/JwtAuthenticationFilter.java
> +        } catch (NotFoundException e) {
하나의 메소드 내 너무 다양한 기능들을 담아둠, 객체지향 관점에서 함수 하나에는 온전히 하나의 기능만 넣어두는 것이 좋음
- 이러한 메소드 내 token 생성 부분이나 유효성 검사 등은 각기 별도 메소드로 분리 시킬 만한듯

2024-11-12 13:25 UTC, GuardJo approved these changes
👍

2024-11-13 04:11 UTC, zz106603 commented on src/main/java/com/edio/common/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler {
> Spring에 기본적인 Exception들에 대한 handling을 지원하는 ResponseEntityExceptionHandler 객체가 존재함
> 
> * 시간 될 때 참고 바람

시간될 때 참고하여 적용 예정

2024-11-13 04:12 UTC, zz106603 commented on src/main/java/com/edio/common/security/CustomUserDetailsService.java
> +    public CustomUserDetailsService(AccountRepository accountRepository) {
> lombok 을 적극적으로 활용합시다
> 
> * 또한 UserDetailsService와 같은 함수형 인터페이스는 구현체를 굳이 구성하지 않아도 Configuration 객체 내 Lambda 형식으로 빼면 코드 수를 보다 더 줄일 수 있음

securityConfig 설정 파일에 Lambda형식으로 빼서 구현체를 제거 함요

2024-11-13 04:19 UTC, zz106603 commented on src/main/java/com/edio/common/security/jwt/JwtAuthenticationFilter.java
> +        } catch (NotFoundException e) {
> 하나의 메소드 내 너무 다양한 기능들을 담아둠, 객체지향 관점에서 함수 하나에는 온전히 하나의 기능만 넣어두는 것이 좋음
> 
> * 이러한 메소드 내 token 생성 부분이나 유효성 검사 등은 각기 별도 메소드로 분리 시킬 만한듯

각 기능들로 메서드 구분 완료

2024-11-13 04:23 UTC, merged