add/ local-prod properties분리 작업
KNU-CSE14/edio_backend pull request #37
Opened 2024-11-12 07:46 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- Local과 Prod로 구분하여 properties 분리
- deploy.sh에 active 설정

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [ ] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-11-12 13:52 UTC, GuardJo requested changes

2024-11-12 13:52 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/repository/FolderRepository.java
> -    List<Folder> findAllAccountIdAndIsDeleted(Long accountId, boolean isDeleted);
#33 이쯤이었나에서 본 형상 같은데..?

2024-11-12 13:52 UTC, GuardJo commented on src/main/resources/application-local.properties
> +spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
application-local.yml이 이미 있는데 추가한 이유가 있는지?

2024-11-12 13:52 UTC, GuardJo commented on src/main/resources/application-prod.properties
properties 쓸지 yaml 쓸지 함 의견 어필 해봐야겠음
- 난 yaml 선호파임 (hierarchy 형태라 가독성이 좋아서)

2024-11-12 14:03 UTC, zz106603 commented on src/main/resources/application-local.properties
> +spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
> application-local.yml이 이미 있는데 추가한 이유가 있는지?

아래 내용처럼 yml파일로 할지 properties로 할지 안정해져서 기존에 했던 properties 기준으로 생성했슴다

2024-11-12 14:04 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/repository/FolderRepository.java
> -    List<Folder> findAllAccountIdAndIsDeleted(Long accountId, boolean isDeleted);
> #33 이쯤이었나에서 본 형상 같은데..?

이 버전으로 git action테스트 해야하는데 현재 main브랜치에서 땄을때 수정버전이 안되어있어서 실행이 안되는 이슈로 이 브랜치에서도 수정여

2024-11-12 22:53 UTC, jsjouo249 commented on src/main/resources/application-prod.properties
properties를 쓴다면 네이밍에
prod용은 그냥 application.properties로 하고,
local용에만 application-local.properties를 하면 좋을 것 같습니다.

2024-11-12 22:53 UTC, jsjouo249 commented on src/main/resources/application-prod.properties
> +spring.security.oauth2.client.registration.google.redirect-uri=http://ec2-43-203-169-54.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google
개행 추가 부탁드려요

2024-11-12 22:54 UTC, jsjouo249 commented on src/main/resources/application.properties
> -
주석이 칸을 나눠주지만, 개행들을 제거한 이유가 따로 있는걸까요?? 아니면 lint가 자동으로 지워준걸까요??

2024-11-13 06:26 UTC, zz106603 commented on src/main/resources/application-prod.properties
> properties를 쓴다면 네이밍에 prod용은 그냥 application.properties로 하고, local용에만 application-local.properties를 하면 좋을 것 같습니다.

일단 local.yml만 수정하고 추후에 전체 다 yml파일로 변경 예정

2024-11-13 06:26 UTC, zz106603 commented on src/main/resources/application.properties
> -
> 주석이 칸을 나눠주지만, 개행들을 제거한 이유가 따로 있는걸까요?? 아니면 lint가 자동으로 지워준걸까요?? 개행이 있는게 가독성이 좀 더 좋아보여서 질문남깁니다

lint가 자동으로 하느라 그렇게 된 것 같고 yml파일로 변경 예정입니다

2024-11-13 06:32 UTC, GuardJo approved these changes
👍

2024-11-13 06:33 UTC, merged