add/ properties를 yml파일로 교체(local, prod, 공통)
KNU-CSE14/edio_backend pull request #39
Opened 2024-11-13 06:42 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- .properties를 .yml로 전체 교체
- local, prod, 공통으로 사용
- active는 SecretKey를 통해 설정되도록 함(로컬은 env에서 local로 설정)

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [ ] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-11-13 11:20 UTC, jsjouo249 approved these changes
LGTM!!

2024-11-13 11:20 UTC, jsjouo249 commented on src/main/java/com/edio/EdioBackendApplication.java
> +        // 로그 출력
확인용이라면 지워도 되지 않을까요??

2024-11-13 16:03 UTC, GuardJo requested changes

2024-11-13 16:03 UTC, GuardJo commented on src/main/java/com/edio/EdioBackendApplication.java
> +        // 로그 출력
옳소

2024-11-13 16:03 UTC, GuardJo commented on src/main/java/com/edio/common/security/SecurityConfig.java
> +                        .successHandler((request, response, authentication) -> {
이정도 사이즈면 SuccessHandler 별도 객체로 빼는건 어떨까요?

2024-11-13 16:03 UTC, GuardJo commented on src/main/java/com/edio/common/security/SecurityConfig.java
> +        configuration.setAllowedOrigins(Arrays.asList("http://localhost:3000"));
이거 FE url이 local용이니 외부 변수로 빼두는게 좋을 듯

2024-11-13 16:03 UTC, GuardJo commented on src/main/java/com/edio/common/security/SecurityConfig.java
> +        configuration.setAllowedOrigins(Arrays.asList("http://localhost:3000"));
아니면 와일드카드로 열거나

2024-11-13 16:03 UTC, GuardJo commented on src/main/java/com/edio/common/security/SecurityConfig.java
> +        configuration.setAllowedMethods(Arrays.asList("GET", "POST", "PUT", "DELETE", "OPTIONS"));
PATCH도 넣어주세요

2024-11-14 07:13 UTC, zz106603 commented on src/main/java/com/edio/common/security/SecurityConfig.java
> +                        .successHandler((request, response, authentication) -> {
> 이정도 사이즈면 SuccessHandler 별도 객체로 빼는건 어떨까요?

완료

2024-11-20 06:46 UTC, GuardJo approved these changes
👍

2024-11-20 07:53 UTC, merged