add: OAuth 로그인 redirectUri 동적으로 요청 처리(state param)
KNU-CSE14/edio_backend pull request #45
Opened 2024-11-28 06:08 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- OAuth 로그인 성공 시 프론트에서 요청한 redirectUri로 응답되도록 수정
- OAuth 요청 시 state를 통해 csrf를 방지하는데 보통 redirectUri를 state 파라미터로 받아서 처리
- state에 csrf용 UUID 생성 및 redirectUri 세팅 후 JSON 포맷 변경
- successHandler에서는 decode를 통해 state검증 및 redirectUri로 응답

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [ ] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-11-28 14:18 UTC, GuardJo requested changes

2024-11-28 14:18 UTC, GuardJo commented on src/main/java/com/edio/common/security/CustomAuthorizationRequestResolver.java
> +    private final ObjectMapper objectMapper = new ObjectMapper(); // JSON 변환용
ObjectMapper는 Spring Boot에서 기본적으로 bean으로 관리되고 있음, 외부에서 bean으로 주입받아 사용하는게 좋을 듯함

2024-11-28 14:18 UTC, GuardJo commented on src/main/java/com/edio/common/security/OAuth2ResolverConfig.java
> +    public OAuth2AuthorizationRequestResolver customAuthorizationRequestResolver(ClientRegistrationRepository clientRegistrationRepository) {
Security 관련 설정 객체는 한 군데 모여 있으니 거기에 합치는게 나을듯함

2024-11-28 14:18 UTC, GuardJo commented on src/main/java/com/edio/common/security/OAuth2SuccessHandler.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
위의 ObjectMapper 관련 코멘트 참고 바람

2024-11-29 06:26 UTC, zz106603 commented on src/main/java/com/edio/common/security/CustomAuthorizationRequestResolver.java
> +    private final ObjectMapper objectMapper = new ObjectMapper(); // JSON 변환용
> ObjectMapper는 Spring Boot에서 기본적으로 bean으로 관리되고 있음, 외부에서 bean으로 주입받아 사용하는게 좋을 듯함

bean주입으로 변경

2024-11-29 06:26 UTC, zz106603 commented on src/main/java/com/edio/common/security/OAuth2ResolverConfig.java
> +    public OAuth2AuthorizationRequestResolver customAuthorizationRequestResolver(ClientRegistrationRepository clientRegistrationRepository) {
> Security 관련 설정 객체는 한 군데 모여 있으니 거기에 합치는게 나을듯함

순환 참조 문제로 추후에 찾아보겠습니다

2024-11-29 14:16 UTC, GuardJo approved these changes
👍

2024-11-30 07:41 UTC, merged