add: account 조회 구현(member 포함)
KNU-CSE14/edio_backend pull request #50
Opened 2024-11-30 08:46 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- account 엔티티에 member를 단방향으로 추가
- account 조회 시에 member도 포함해서 조회
- 회원가입 시점에 member 생성 -> account 생성 -> rootFolder 생성으로 행

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [x] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-12-02 14:45 UTC, GuardJo requested changes

2024-12-02 14:45 UTC, GuardJo commented on src/main/java/com/edio/common/security/jwt/JwtAuthenticationFilter.java
> +        httpResponse.addHeader("Set-Cookie", accessTokenCookie);
"Set-Cookie" 와 같은 리터럴 값 말고 spring에서 헤더들에 대한 enum 타입을 제공함 (HttpHeaders)
- 혹은 addHeader가 아닌 addCookie() 메소드를 사용하는 것이 더 나을 듯 함

2024-12-02 14:45 UTC, GuardJo commented on src/main/java/com/edio/common/security/jwt/JwtTokenProvider.java
> +        Long accountId = accountService.getAccountIdByLoginId(loginId);
이미 로그인 요청 시점에 DB 조회를 통해 관련 정보를 1차적으로 취득 했으나, 인증 객체 (여기선 CustomOAuth2User) 에는 관련 값들을 사용치 않고 있어서 토큰 조회 시점에 accountId 를 찾기 위해 또 DB에 접근하는 것은 비효율적임

- 인증 객체를 커스텀하지 않았나 싶어 CustomOAuth2User 구현체를 보니 그저 OAuth2User 인터페이스를 호출하는게 다임, 관련 구현체에 로그인 시점에 accountId 나 별도 추가로 필요한 요소들을 추가하여 확장하는 것이 올바름 (구현체 안에서 해당 인터페이스를 호출하는 것 자체가 이상함)
- 인증 객체에 대한 구현체를 리팩토링 하여 별도 최초 인증객체 구성 시점에 이미 필요한 정보들을 들고 있을 필요가 있음

2024-12-02 14:45 UTC, GuardJo commented on src/main/java/com/edio/common/security/jwt/JwtAuthenticationFilter.java
> +                        accountId,
principal엔 보통 식별키(username) 이 아닌 UserDetails 에 대한 구현체를 통째로 넣어두는 것이 좋음, 사용자 식별 뿐 아니라 해당 사용자가 지닌 각종 정보를 별도에 추가 호출 필요 없이 인증 객체에서 꺼낼 수 있기 때문이며, 실제로 UserDetails에 대한 구현체들은 타고 들어가면 Principal 을 상위 객체로 두고 있음
- 현 모듈에선  CustomIOAuth2User가 적절함

2024-12-02 14:45 UTC, GuardJo commented on src/main/java/com/edio/user/controller/MemberController.java
> +    public MemberResponse createAccount(@RequestBody MemberCreateRequest memberCreateRequest) {
그러고보니 Member 를 외부에서 등록할 일이 있나?

2024-12-02 14:45 UTC, GuardJo commented on src/test/java/com/edio/common/security/jwt/JwtTokenProviderTest.java
> +        jwtTokenProvider = new JwtTokenProvider(userDetailsService, accountService, secretKey);
구성 코드 보니 JwtTokenProvider에 모킹한 객체들 넣어서 테스트 하고 싶은듯 한데, @Mock 어노테이션과 함께 @ExtendsMock 과 MockitoExtension 확인해보는면 좋음, 원하는 방향이 모킹한거 주입하고 싶은거면 해당 어노테이션들을 사용하면 됨

2024-12-02 14:45 UTC, GuardJo commented on src/test/java/com/edio/common/security/jwt/JwtTokenProviderTest.java
> +        jwtTokenProvider = new JwtTokenProvider(userDetailsService, accountService, secretKey);
뭐야 아래 보니 쓸 줄 아는데 왜 어려운 길로 돌아가는지?

2024-12-02 14:45 UTC, GuardJo commented on src/test/java/com/edio/service/AccountServiceTests.java
> +        Member mockMember = Member.builder()
중복되는 테스트 데이터들은 매번 만들지 말고 필드에 선언해두고 쓰면 편함

2024-12-02 14:45 UTC, GuardJo commented on src/test/java/com/edio/service/FolderServiceTests.java
> +//    public void createFolder_whenFolderExists_returnsExistingFolder() {
주석으로 두는 이유가 있는지?

2024-12-03 04:55 UTC, zz106603 commented on src/main/java/com/edio/common/security/jwt/JwtAuthenticationFilter.java
> +        httpResponse.addHeader("Set-Cookie", accessTokenCookie);
> "Set-Cookie" 와 같은 리터럴 값 말고 spring에서 헤더들에 대한 enum 타입을 제공함 (HttpHeaders)
> 
> * 혹은 addHeader가 아닌 addCookie() 메소드를 사용하는 것이 더 나을 듯 함

addCookie는 sameSite를 지원하지 않아서 HttpHeaders 적용합니다

2024-12-03 05:08 UTC, zz106603 commented on src/main/java/com/edio/common/security/jwt/JwtTokenProvider.java
> +        Long accountId = accountService.getAccountIdByLoginId(loginId);
> 이미 로그인 요청 시점에 DB 조회를 통해 관련 정보를 1차적으로 취득 했으나, 인증 객체 (여기선 CustomOAuth2User) 에는 관련 값들을 사용치 않고 있어서 토큰 조회 시점에 accountId 를 찾기 위해 또 DB에 접근하는 것은 비효율적임
> 
> * 인증 객체를 커스텀하지 않았나 싶어 CustomOAuth2User 구현체를 보니 그저 OAuth2User 인터페이스를 호출하는게 다임, 관련 구현체에 로그인 시점에 accountId 나 별도 추가로 필요한 요소들을 추가하여 확장하는 것이 올바름 (구현체 안에서 해당 인터페이스를 호출하는 것 자체가 이상함)
> * 인증 객체에 대한 구현체를 리팩토링 하여 별도 최초 인증객체 구성 시점에 이미 필요한 정보들을 들고 있을 필요가 있음

CustomOAuth2User객체에 accountId를 추가해서 jwt token생성시점에 저장된 accountId를 조회하도록 수정

2024-12-03 05:10 UTC, zz106603 commented on src/main/java/com/edio/user/controller/MemberController.java
> +    public MemberResponse createAccount(@RequestBody MemberCreateRequest memberCreateRequest) {
> 그러고보니 Member 를 외부에서 등록할 일이 있나?

등록할 일 없는데 API 테스트 하느라 남겨뒀던거고 추후에 삭제 예정이요~

2024-12-03 06:35 UTC, zz106603 commented on src/main/java/com/edio/common/security/jwt/JwtAuthenticationFilter.java
> +                        accountId,
> principal엔 보통 식별키(username) 이 아닌 UserDetails 에 대한 구현체를 통째로 넣어두는 것이 좋음, 사용자 식별 뿐 아니라 해당 사용자가 지닌 각종 정보를 별도에 추가 호출 필요 없이 인증 객체에서 꺼낼 수 있기 때문이며, 실제로 UserDetails에 대한 구현체들은 타고 들어가면 Principal 을 상위 객체로 두고 있음
> 
> * 현 모듈에선  CustomIOAuth2User가 적절함

CustomUserDetails 생성해서 인증 정보 저장되도록 수정, CustomOAuth2User 삭제

2024-12-03 06:56 UTC, zz106603 commented on src/test/java/com/edio/common/security/jwt/JwtTokenProviderTest.java
> +        jwtTokenProvider = new JwtTokenProvider(userDetailsService, accountService, secretKey);
> 구성 코드 보니 JwtTokenProvider에 모킹한 객체들 넣어서 테스트 하고 싶은듯 한데, @mock 어노테이션과 함께 @ExtendsMock 과 MockitoExtension 확인해보는면 좋음, 원하는 방향이 모킹한거 주입하고 싶은거면 해당 어노테이션들을 사용하면 됨

JwtTokenProvider에 @InjectMocks를 사용하려면 필요한 변수가 @Mock으로 선언이 되어야 하는데 secretKey같은 경우 String 타입이라 이거는 @Mock으로 선언이 안됨. 그래서 @InjectMocks를 사용할 수 없고 @ExtendWith를 사용해서 openMocks처럼 수동으로 선언한거는 처리 완료

2024-12-03 07:16 UTC, zz106603 commented on src/test/java/com/edio/service/AccountServiceTests.java
> +        Member mockMember = Member.builder()
> 중복되는 테스트 데이터들은 매번 만들지 말고 필드에 선언해두고 쓰면 편함

필드 선언 완료

2024-12-03 07:16 UTC, zz106603 commented on src/test/java/com/edio/service/FolderServiceTests.java
> +//    public void createFolder_whenFolderExists_returnsExistingFolder() {
> 주석으로 두는 이유가 있는지?

현재 폴더명 중복 처리에 대해서 아직 결정된게 없어서 주석 처리

2024-12-04 15:22 UTC, GuardJo requested changes

2024-12-04 15:22 UTC, GuardJo commented on src/main/java/com/edio/common/security/CustomOAuth2UserService.java
> +            accountResponse = accountService.findOneAccount(accountId);
두 번 호출 할 필요 없이 두 메소드 하나로 합칠 수 있을 듯함
- AccountResponse 내 id 가 accountId 아님?

2024-12-05 03:59 UTC, zz106603 commented on src/main/java/com/edio/common/security/CustomOAuth2UserService.java
> +            accountResponse = accountService.findOneAccount(accountId);
> 두 번 호출 할 필요 없이 두 메소드 하나로 합칠 수 있을 듯함
> 
> * AccountResponse 내 id 가 accountId 아님?

catch에 걸리는거라 account가 이미 있는 상황에서는 accountResponse를 만들어내야 하는건데 이건 그럼 기존 방식으로 accountId 조회 말고 email로 조회하는걸로 변경?

2024-12-05 04:36 UTC, GuardJo approved these changes
👍

2024-12-05 04:56 UTC, merged