add: Category, Deck API 기능 개발 및 Folder 조회 방식 수정
KNU-CSE14/edio_backend pull request #53
Opened 2024-12-05 08:12 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- Category API 개발(조회)
- Deck API 개발(등록)
- Folder 하위 조회 API 수정(Folder, Deck 포함 1depth)

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [x] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-12-06 16:12 UTC, GuardJo requested changes

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/common/exception/BadRequestException.java
> +@Getter
Getter 가 왜 필요한가요?

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/controller/DeckController.java
> +    @PatchMapping("/deck/{id}/move")
Restful API 에선 동사는 지양 합니다🙏

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/domain/Deck.java
> +    @ManyToOne(fetch = FetchType.LAZY)
어차피 덱 선택 하면 카테고리도 표시해줘야 될텐데 굳이 lazeLoading 으로 해서 그 시점에 쿼리를 다시 날리는것보단 한 EAGER로 Deck 조회할 때 한번에 가져오는게 좋을 듯 함

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/model/request/DeckCreateRequest.java
> +    private String deckType;
이런건 enum으로 쓰는게 더 나을 듯함

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/model/request/DeckCreateRequest.java
> +    private String deckType;
전에도 한번 언급한거 같은데 단순 String은 어떠한 문자열이든 들어올 수 있는 위험 부담이 존재함

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/model/request/DeckMoveRequest.java
> +    private Long parentId; // 새로운 폴더 ID
이거 위에 엔드포인트 메소드에서 id를 pathVariable로 받을 필요 없이 여기에서 이동할 폴더의 id 값을 가지고 있으면 되지 않나?

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/model/request/DeckMoveRequest.java
> +    private Long parentId; // 새로운 폴더 ID
아 근데 이건 뭐 이 방법이나 저 방법이나 취향 차이 인거 같기도 하고...?

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/model/response/DeckResponse.java
> +public class DeckResponse {
근데 어떤 vo는 record고 어떤 vo는 class인데 이건 통일하는게 나을 듯함
- 다른 사람들이 해당 요소들 사용할 때 헷갈림 (어떤 건 class라 getXXX() 메소드 등이고, 어떤건 record라 xxx() 이라던가?

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +            newFolder = entityManager.getReference(Folder.class, newFolderId);
이 분 getRefernceById() 쓰고 싶었던거 같은데 까먹어서 EntityManager bean을 가져와 버린거 같은데...?

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +        if (deck.getFolder() != null && deck.getFolder().equals(newFolder)) {
이거 의도한 동작이랑 실제 구현이 안맞음
현재 Deck의 Folder Entity 와 newFolder의 Entity는 동일한 데이터를 가져왔더라도 다른 인스턴스임
- Folder Entity에서 별도의 equals() 재정의를 하지 않았기에 서로 다른 인스턴스이기에 무조건 false임
- 또한 getReference() 혹은 getRefernceById()를 통해 가져온 객체는 내부적으론 Entity 객체가 아니라 proxy 객체이기에 다른 인스턴스임

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +        deck.setFolder(newFolder);
위에서 같은 폴더로 변경 했을 경우 괜히 쿼리 또 날릴까봐 위에서 같은 폴더 인 경우 별도 제외 처리 한거 같은데
의도는 좋았으나 사실 JPA에서는 Transaction 상에 올라온 Entity의 변경 여부를 감지하는데, 어차피 동일한 Folder면Transaction 끝날 때 수정 쿼리를 날리지 않음

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/domain/Deck.java
> +    @JoinColumn(name = "folder_id", nullable = false)
아 얘도 어차피 DeckResponse로 반환할 때 forderId 필요하고, 그 때 가서 lazyLoadind 에 의해 FOLDER 테이블 조회 쿼리를 날리게 되므로, 어차피 사용할거면 EAGER로 두는 게 나음
- EAGER로 두면 쿼리 한번에 가져올텐데, LAZY로 하니 괜히 두세번 쿼리 날려야함
- LAZY 를 쓸 경우에는 해당 필드가 필요한 부분이 제한적일 때 좋으나, 현재는 DeckResponse 만들 때 무조건 호출하게 되어 있음

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/model/response/DeckResponse.java
> +        return new DeckResponse(deck.getId(),
시간될 때 ModelMapper 훑어보셈
이런 단순 mapping 및 converting 에 따른 보일러 코드를 줄여주는데 획기적인 라이브러리임

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/model/response/FolderWithDeckResponse.java
> +    public static class SubDeck {
얘랑 아래꺼랑 내부에서만 쓰는데 굳이 접근제한자를 public으로 둘 필요가 있는지?

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/model/response/FolderWithDeckResponse.java
> +    public static FolderWithDeckResponse from(Folder folder) {
이렇게 조합해서 만드는 것을 보니 JPA의 Projection도 슬 먼지 찾아 볼 때가 된 듯 함

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +            newParentFolder = entityManager.getReference(Folder.class, newParentId);
{JpaRepository}.getRefernceById()

2024-12-06 16:12 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        Folder folderToMove = folderRepository.findByIdAndIsDeleted(folderId, false)
Java에선 변수명은 명사, 메소드명은 동사가 관례임
- 헷갈림

2024-12-09 04:10 UTC, zz106603 commented on src/main/java/com/edio/common/exception/BadRequestException.java
> +@Getter
> Getter 가 왜 필요한가요?

필요없는거 확인하고 삭제요

2024-12-09 04:20 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/domain/Deck.java
> +    @ManyToOne(fetch = FetchType.LAZY)
> 어차피 덱 선택 하면 카테고리도 표시해줘야 될텐데 굳이 lazeLoading 으로 해서 그 시점에 쿼리를 다시 날리는것보단 한 EAGER로 Deck 조회할 때 한번에 가져오는게 좋을 듯 함

확인했고, @ManyToOne의 기본값이 EAGER이기 때문에 제외했슴다

2024-12-09 04:20 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/domain/Deck.java
> +    @ManyToOne(fetch = FetchType.LAZY)
> > 어차피 덱 선택 하면 카테고리도 표시해줘야 될텐데 굳이 lazeLoading 으로 해서 그 시점에 쿼리를 다시 날리는것보단 한 EAGER로 Deck 조회할 때 한번에 가져오는게 좋을 듯 함
> 
> 확인했고, ManyToOne의 기본값이 EAGER이기 때문에 제외했슴다

2024-12-09 04:31 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/model/request/DeckCreateRequest.java
> +    private String deckType;
> 이런건 enum으로 쓰는게 더 나을 듯함

deckType을 isShared로 변경, String타입을 Boolean으로 변경

2024-12-09 04:32 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/model/request/DeckMoveRequest.java
> +    private Long parentId; // 새로운 폴더 ID
> 이거 위에 엔드포인트 메소드에서 id를 pathVariable로 받을 필요 없이 여기에서 이동할 폴더의 id 값을 가지고 있으면 되지 않나?

일단은 엔드포인트가 특정 id에 대한 하위 동작을 나타내는거는 이런식으로 하는게 낫다고 본 것 같아서 추후에 수정이 필요하면 수정할게여

2024-12-09 05:08 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/model/response/DeckResponse.java
> +public class DeckResponse {
> 근데 어떤 vo는 record고 어떤 vo는 class인데 이건 통일하는게 나을 듯함
> 
> * 다른 사람들이 해당 요소들 사용할 때 헷갈림 (어떤 건 class라 getXXX() 메소드 등이고, 어떤건 record라 xxx() 이라던가?

record로 통일

2024-12-09 05:08 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +            newFolder = entityManager.getReference(Folder.class, newFolderId);
> 이 분 getRefernceById() 쓰고 싶었던거 같은데 까먹어서 EntityManager bean을 가져와 버린거 같은데...?

수정 완료요 ㅎ

2024-12-09 05:14 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +        if (deck.getFolder() != null && deck.getFolder().equals(newFolder)) {
> 이거 의도한 동작이랑 실제 구현이 안맞음 현재 Deck의 Folder Entity 와 newFolder의 Entity는 동일한 데이터를 가져왔더라도 다른 인스턴스임
> 
> * Folder Entity에서 별도의 equals() 재정의를 하지 않았기에 서로 다른 인스턴스이기에 무조건 false임
> * 또한 getReference() 혹은 getRefernceById()를 통해 가져온 객체는 내부적으론 Entity 객체가 아니라 proxy 객체이기에 다른 인스턴스임

내용 확인했고 setUpdate시에 JPA에서 자동으로 확인 후 update해주는 개념 확인으로 이 부분 삭제요

2024-12-09 05:17 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/model/response/FolderWithDeckResponse.java
> +    public static class SubDeck {
> 얘랑 아래꺼랑 내부에서만 쓰는데 굳이 접근제한자를 public으로 둘 필요가 있는지?

record로 변경하고 private로 수정

2024-12-09 05:20 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/service/FolderServiceImpl.java
> +        Folder folderToMove = folderRepository.findByIdAndIsDeleted(folderId, false)
> Java에선 변수명은 명사, 메소드명은 동사가 관례임
> 
> * 헷갈림

folder로 변경

2024-12-09 05:23 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/deck/model/response/DeckResponse.java
> +        return new DeckResponse(deck.getId(),
> 시간될 때 ModelMapper 훑어보셈 이런 단순 mapping 및 converting 에 따른 보일러 코드를 줄여주는데 획기적인 라이브러리임

다음 PR에 진행할게여

2024-12-09 05:23 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/model/response/FolderWithDeckResponse.java
> +    public static FolderWithDeckResponse from(Folder folder) {
> 이렇게 조합해서 만드는 것을 보니 JPA의 Projection도 슬 먼지 찾아 볼 때가 된 듯 함

다음 PR에 진행할게여

2024-12-10 04:35 UTC, GuardJo approved these changes
👍

2024-12-10 05:05 UTC, merged