Add/ Deck, Attachment API 개발(덱 등록, 수정, 삭제 첨부파일 API 연동)
KNU-CSE14/edio_backend pull request #65
Opened 2024-12-17 06:53 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- Deck 등록, 수정, 삭제 Attachment, AttachmentDeckTarget과 연동
- Controller Request 구조 표준화(request 클래스)
- Attachment는 소프트 삭제, AttachmentDeckTarget은 row 보관
- 첨부 파일 수정이나 삭제 시점에는 Attachment 소프트 삭제

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [x] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-12-19 02:34 UTC, GuardJo requested changes

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/attachment/service/AttachmentServiceImpl.java
> +                .fileTarget(target)
FileTarget Enum 타입 만들지 않았나요?

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/attachment/service/AttachmentServiceImpl.java
> +        deck.getAttachmentDeckTargets().add(attachmentDeckTarget);
mappedBy로 매핑되어 있는 쪽에선 어차피 삽입 쿼리 적용 안됨
- mappedBy는 조회만 되기에, 위에서 어차피 AttachmentDeckTarget에 deck 넣어주었으므로 여기선 안넣어도 됨

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/model/response/DeckResponse.java
> +                Optional.ofNullable(deck.getAttachmentDeckTargets())
Deck Entity 객체 보면 atttachmentDeckTarget이 null일 경우가 없기에 굳이 null 체크 안해도 될 듯?

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +                String attachmentFolder = String.valueOf(AttachmentFolder.IMAGE.getValue());
getValue()의 반환 타입이 이미 String인데 또 String으로 변환하는 이유가 있는지?

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +                String fileTarget = String.valueOf(FileTarget.DECK);
Enum 타입은 내부적으로 name() 메소드를 지원함

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +                String fileTarget = String.valueOf(FileTarget.DECK);
아 근데 넣는거 보니 애초에 Entity의 필드를 Enum으로 뒀어도 되지 않나?

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +        if (request.name() != null && !request.name().isBlank()) {
Spring에서 제공하는 StringUtils의 hasText() 메소드에 관련 필터링 다 적용되어 있음
- Spring에서 제공하는 유틸 객체들 쓸만한거 많음 ex) 문자열 관련 유틸은 StringUtils, 컬렉션 관련 유틸은 CollectionUtils 등

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +        if (request.description() != null && !request.description().isBlank()) {
위랑 동일

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +                String attachmentFolder = String.valueOf(AttachmentFolder.IMAGE.getValue());
위랑 동일한 이슈

2024-12-19 02:34 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/deck/service/DeckServiceImpl.java
> +                String fileTarget = String.valueOf(FileTarget.DECK);
위랑 동일한 이슈

2024-12-19 02:34 UTC, GuardJo commented on src/test/java/com/edio/service/AttachmentServiceTests.java
> +        MultipartFile mockFile = mock(MultipartFile.class);
애초에 Mock용으로 MockMultipartFile 구현체가 존재함

2024-12-19 04:25 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/attachment/service/AttachmentServiceImpl.java
> +                .fileTarget(target)
> FileTarget Enum 타입 만들지 않았나요?

덱, 카드 통합으로 attachment 저장하는 메서드이고 파라미터로 deck인지 card인지 받아서 처리하려고 target으로 변수 받은건데 그 질문 맞나요?

2024-12-19 04:42 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/attachment/service/AttachmentServiceImpl.java
> +                .fileTarget(target)
> FileTarget Enum 타입 만들지 않았나요?

ENUM은 메서드 호출 전에 사용해서 넘겨주는 식으로 사용

2024-12-19 04:43 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/attachment/service/AttachmentServiceImpl.java
> +        deck.getAttachmentDeckTargets().add(attachmentDeckTarget);
> mappedBy로 매핑되어 있는 쪽에선 어차피 삽입 쿼리 적용 안됨
> 
> * mappedBy는 조회만 되기에, 위에서 어차피 AttachmentDeckTarget에 deck 넣어주었으므로 여기선 안넣어도 됨

덱 생성 response 객체에는 덱ID만 필요하기 때문에 attachment없는 이슈는 문제 없을듯

2024-12-20 15:57 UTC, GuardJo approved these changes
👍

2024-12-21 06:47 UTC, merged