Add/folder api 개발(사용자 폴더 목록 조회)
KNU-CSE14/edio_backend pull request #76
Opened 2024-12-31 03:17 UTC by zz106603

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] ⚰️ Maintain (keep in good condition or in working)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- 사용자(AccountID) 기준 폴더 목록 조회
- id, name 조회를 위한 UserFolderResponse 추가
- folder 패키지에 사용되는 예외처리 공통 ErorrMessages 처리(404 NotFound, 409 Conflict)

### 📝 Checklist

- [x] 🔴 Human eyes (no test)
- [x] 🟡 swagger or Smoke test
- [ ] 🟢 unit test or CI test

### 📸 Log/Screenshot

🌱 before

🏡 after

2024-12-31 10:07 UTC, GuardJo requested changes

2024-12-31 10:07 UTC, GuardJo commented on src/main/java/com/edio/common/exception/custom/NotFoundException.java
> +        super(HttpStatus.NOT_FOUND, String.format("%s " + ErrorMessages.NOT_FOUND + ": %s", entityClass.getSimpleName(), message));
처음부터 궁금했던건데 Custom Exception들이 전부 이미 있고, 이름도 똑같은데 별도로 만든 이유가 상태코드 매핑이 목적임? 아니면 message 매번 주입하기 귀찮아서임?

2024-12-31 10:07 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/controller/FolderController.java
> +    @GetMapping("/folder/user")
윤환님 네이밍 센스좀...
그간 계정에는 account 라는 명칭으로 쓰여있었는데 얘만 user 인것도 이상하고, 내 폴더 느낌을 바랬는데, url만 보고 먼지 명확하지 않음 (/folders/my-folder 나 /my-folders 나 기타 등등, 좀 더 명확했으면 함)

2024-12-31 10:07 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/repository/FolderRepository.java
> +    Optional<Folder> findByIdAndIsDeletedFalse(Long id);
헷갈리지 않게 파라미터명이라도 바꿔주세요
- 그리고 주석 남길거면 사용하는 입장에서도 javadoc으로 알 수 있게끔 javadoc 주석으로 하는게 좋을 듯 합니다.

2025-01-02 06:04 UTC, zz106603 commented on src/main/java/com/edio/common/exception/custom/NotFoundException.java
> +        super(HttpStatus.NOT_FOUND, String.format("%s " + ErrorMessages.NOT_FOUND + ": %s", entityClass.getSimpleName(), message));
> 처음부터 궁금했던건데 Custom Exception들이 전부 이미 있고, 이름도 똑같은데 별도로 만든 이유가 상태코드 매핑이 목적임? 아니면 message 매번 주입하기 귀찮아서임?

전 회사에서 메시지들은 따로 관리 했던거 같아서 최대한 실무처럼 해보려고 적용해본거긴한데 의견좀 부탁드림여

2025-01-02 08:30 UTC, GuardJo approved these changes
👍

2025-01-02 08:30 UTC, GuardJo commented on src/main/java/com/edio/common/exception/custom/NotFoundException.java
> +        super(HttpStatus.NOT_FOUND, String.format("%s " + ErrorMessages.NOT_FOUND + ": %s", entityClass.getSimpleName(), message));
메시지는 별도로 커스텀하는거 좋은데, 예외들이 전부 이미 java나 프레임워크에서 제공하는 수준의 추상화로 구성되어 있어서 문의 드렸습니다.

말씀하신 에러메시지는 도메인별로 아무래도 제각각이니 따로 빼는건 좋으나, 현시점 기준으론 예외들은 크게 독립적인 시나리오들은 없어보였습니다.

추후, 기회가 된다면 BE 분들과 논의해도 좋을 듯 하네요

2025-01-02 08:31 UTC, GuardJo requested changes

2025-01-02 08:31 UTC, GuardJo commented on src/main/java/com/edio/studywithcard/folder/controller/FolderController.java
> +    @GetMapping("/folders/my-folders")
아 제가 folders 라고 쓰긴 했는데, 지금 다른 애들 다 단수형으로 url 구성해놨으니 이것도 단수형으로 가는게 좋을 듯합니다.

2025-01-02 08:40 UTC, zz106603 commented on src/main/java/com/edio/studywithcard/folder/controller/FolderController.java
> +    @GetMapping("/folders/my-folders")
> 아 제가 folders 라고 쓰긴 했는데, 지금 다른 애들 다 단수형으로 url 구성해놨으니 이것도 단수형으로 가는게 좋을 듯합니다.

일단 folder/my-folders로 두고 나중에 의논해서 수정할게요~

2025-01-02 08:47 UTC, GuardJo approved these changes
👍

2025-01-02 08:49 UTC, merged